version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10
only-tagged-commits: &only-tagged-commits
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Tests
          command: npm test
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/lcov.info
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Setup .npmrc credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm run build
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build
  build-deploy:
    jobs:
      - build: *only-tagged-commits
      - publish:
          <<: *only-tagged-commits
          requires:
            - build
